[package]
name = "atomize-macro"
version = "0.1.0"
authors = ["Brandon Dyer <brandondyer64@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = "0.5.11"
quote = "1.0.3"
syn = "1.0.16"
