[package]
authors = ["Brandon Dyer"]
description = "Macros for the atomize crate"
edition = "2018"
license = "MIT"
name = "atomize-macro"
version = "0.1.3"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
